import type { SpecPipeline } from 'src/types'
import {
  dataset,
  xBand,
  yLinear,
  initArea,
  stackInverse,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  datasetPivotPlaceholder,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotAdapter,
  initPivot,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  lineStyle,
  areaStyle,
  verticalCrosshairLine,
} from '../pipes'

const area: SpecPipeline = [
  initArea,
  stackInverse,
  color,
  backgroundColor,
  dataset,
  xBand,
  yLinear,
  label,
  tooltip,
  verticalCrosshairLine,
  discreteLegend,
  pointStyle,
  lineStyle,
  areaStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotArea: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initArea,
    color,
    backgroundColor,
    stackInverse,
    datasetPivotPlaceholder,
    xBand,
    yLinear,
    label,
    tooltip,
    verticalCrosshairLine,
    pointStyle,
    lineStyle,
    areaStyle,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const areaSpecPipeline = [pivotAdapter(area, pivotArea)]
