import type { SpecPipeline } from 'src/types'
import {
  dataset,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotIndicators,
  initPivot,
  datasetPivot,
  pivotAdapter,
  datasetPivotPlaceholder,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  initRoseParallel,
  radiusAxis,
  angleAxis,
} from '../pipes'

const roseParallel: SpecPipeline = [
  initRoseParallel,
  stackCornerRadius,
  color,
  backgroundColor,
  dataset,
  radiusAxis,
  angleAxis,
  label,
  tooltip,
  discreteLegend,
  verticalCrosshairRect,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotRoseParallel: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initRoseParallel,
    stackCornerRadius,
    color,
    backgroundColor,
    datasetPivotPlaceholder,
    radiusAxis,
    angleAxis,
    label,
    tooltip,
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const roseParallelSpecPipeline: SpecPipeline = [pivotAdapter(roseParallel, pivotRoseParallel)]
