export { reshapeTo2D1M } from './reshapeTo2D1M'
export { reshapeTo1D1M } from './reshapeTo1D1M'
export { reshapeTo1D2M } from './reshapeTo1D2M'
export { reshapeTo1D } from './reshapeTo1D'
export { pivotReshapeTo1D1M } from './pivotReshapeTo1D1M'
export { pivotReshapeTo1D2M } from './pivotReshapeTo1D2M'
export { pivotReshapeTo2D1M } from './pivotReshapeTo2D1M'
export { pivotReshapeTo1D } from './pivotReshapeTo1D'
