import type { SpecPipeline } from 'src/types'
import {
  percent,
  datasetXY,
  xBand,
  yLinear,
  initArea,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotAdapter,
  initPivot,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  stackInverse,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  lineStyle,
  areaStyle,
  verticalCrosshairLine,
} from '../pipes'

const areaPercent: SpecPipeline = [
  initArea,
  stackInverse,
  color,
  backgroundColor,
  percent,
  datasetXY,
  xBand,
  yLinear,
  label,
  tooltip,
  verticalCrosshairLine,
  discreteLegend,
  pointStyle,
  lineStyle,
  areaStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotAreaPercent: SpecPipeline = [
  initPivot,

  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initArea,
    stackInverse,
    color,
    backgroundColor,
    percent,
    datasetXY,
    xBand,
    yLinear,
    label,
    tooltip,
    verticalCrosshairLine,
    pointStyle,
    lineStyle,
    areaStyle,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const areaPercentSpecPipeline = [pivotAdapter(areaPercent, pivotAreaPercent)]
