import type { SpecPipeline } from 'src/types'
import {
  datasetXY,
  xBand,
  yLinear,
  backgroundColor,
  label,
  datasetPivot,
  pivotIndicators,
  pivotAdapter,
  initPivot,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  verticalCrosshairLine,
  initAreaRange,
  series,
  lineStyle,
  pointStyle,
  pointStateDimensionHover,
  areaStyle,
  progressive,
  tooltipAreaRange,
  tooltipDisable,
} from '../pipes'
import { initAreaRangeLine1, initAreaRangeLine2 } from '../pipes/init/areaRange'

const areaRange: SpecPipeline = [
  series(
    [initAreaRange, areaStyle],
    [initAreaRangeLine1, lineStyle, pointStyle, pointStateDimensionHover, tooltipDisable],
    [initAreaRangeLine2, lineStyle, pointStyle, pointStateDimensionHover, tooltipDisable],
  ),
  datasetXY,
  progressive,
  backgroundColor,
  xBand,
  yLinear,
  label,
  tooltipAreaRange,
  verticalCrosshairLine,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotAreaRange: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    series(
      [initAreaRange, areaStyle],
      [initAreaRangeLine1, lineStyle, pointStyle, pointStateDimensionHover, tooltipDisable],
      [initAreaRangeLine2, lineStyle, pointStyle, pointStateDimensionHover, tooltipDisable],
    ),
    backgroundColor,
    datasetXY,
    progressive,
    xBand,
    yLinear,
    label,
    tooltipAreaRange,
    verticalCrosshairLine,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
]

export const areaRangeSpecPipeline = [pivotAdapter(areaRange, pivotAreaRange)]
