import type { SpecPipeline } from 'src/types'
import {
  initBar,
  datasetYX,
  xLinear,
  yBand,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsCol,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  horizontalCrosshairRect,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  barMaxWidth,
} from '../pipes'

const bar: SpecPipeline = [
  initBar,
  stackCornerRadius,
  barMaxWidth,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetYX,
  progressive,
  xLinear,
  yBand,
  label,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  horizontalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotBar: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsCol,
  datasetPivot,
  pivotIndicators([
    initBar,
    stackCornerRadius,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetYX,
    progressive,
    xLinear,
    yBand,
    label,
    tooltip,
    colorBarStyleFill(barStyle),
    horizontalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const barSpecPipeline: SpecPipeline = [pivotAdapter(bar, pivotBar)]
