import type { SpecPipeline } from 'src/types'
import {
  datasetYX,
  xLinear,
  yBand,
  initBarParallel,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsCol,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  horizontalCrosshairRect,
  stackCornerRadius,
  progressive,
  linearColor,
  colorAdapter,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  barMaxWidth,
  barGapInGroup,
  pivotAxisStyle,
  pivotTitle,
} from '../pipes'

const barParallel: SpecPipeline = [
  initBarParallel,
  stackCornerRadius,
  barMaxWidth,
  barGapInGroup,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetYX,
  progressive,
  xLinear,
  yBand,
  label,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  horizontalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotBarParallel: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsCol,
  datasetPivot,
  pivotIndicators([
    initBarParallel,
    stackCornerRadius,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetYX,
    xLinear,
    pivotAxisStyle(yBand),
    label,
    tooltip,
    colorBarStyleFill(barStyle),
    horizontalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const barParallelSpecPipeline: SpecPipeline = [pivotAdapter(barParallel, pivotBarParallel)]
