import type { SpecPipeline } from 'src/types'
import {
  datasetYX,
  xLinear,
  yBand,
  initBarParallel,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsCol,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  horizontalCrosshairRect,
  stackCornerRadius,
} from '../pipes'

const barParallel: SpecPipeline = [
  initBarParallel,
  stackCornerRadius,
  color,
  backgroundColor,
  datasetYX,
  xLinear,
  yBand,
  label,
  tooltip,
  horizontalCrosshairRect,
  discreteLegend,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotBarParallel: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsCol,
  datasetPivot,
  pivotIndicators([
    initBarParallel,
    stackCornerRadius,
    color,
    backgroundColor,
    datasetYX,
    xLinear,
    yBand,
    label,
    tooltip,
    horizontalCrosshairRect,
    barStyle,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const barParallelSpecPipeline: SpecPipeline = [pivotAdapter(barParallel, pivotBarParallel)]
