import type { SpecPipeline } from 'src/types'
import {
  backgroundColor,
  label,
  tooltipBoxplot,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsCol,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  initBoxplot,
  xBand,
  yLinear,
  verticalCrosshairRect,
  datasetBoxplot,
} from '../pipes'

const boxplot: SpecPipeline = [
  initBoxplot,
  stackCornerRadius,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetBoxplot,
  progressive,
  xBand,
  yLinear,
  label,
  tooltipBoxplot,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotBoxplot: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsCol,
  datasetPivot,
  pivotIndicators([
    initBoxplot,
    stackCornerRadius,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetBoxplot,
    progressive,
    xBand,
    yLinear,
    label,
    tooltipBoxplot,
    colorBarStyleFill(barStyle),
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const boxplotSpecPipeline: SpecPipeline = [pivotAdapter(boxplot, pivotBoxplot)]
