import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  backgroundColor,
  label,
  tooltipBoxplot,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  initBoxplot,
  xBand,
  yLinear,
  verticalCrosshairRect,
  datasetBoxplot,
  pivotAxisStyle,
  pivotTitle,
} from '../pipes'
import { boxLegend } from '../pipes/legend/boxLegend'

const boxplot: VChartSpecPipeline = [
  initBoxplot,
  stackCornerRadius,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetBoxplot,
  progressive,
  xBand,
  yLinear,
  label,
  tooltipBoxplot,
  colorAdapter(boxLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotBoxplot: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  datasetPivot,
  pivotIndicators([
    initBoxplot,
    stackCornerRadius,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetBoxplot,
    progressive,
    xBand,
    pivotAxisStyle(yLinear),
    label,
    tooltipBoxplot,
    colorBarStyleFill(barStyle),
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const boxplotSpecPipeline = [pivotAdapter(boxplot, pivotBoxplot)]
