import type { PivotChartSpecPipeline, VChartSpecPipeline } from 'src/types'
import {
  datasetXY,
  xBand,
  yLinear,
  initColumnParallel,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotIndicators,
  initPivot,
  datasetPivot,
  pivotAdapter,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  progressive,
  linearColor,
  colorAdapter,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  barMaxWidth,
  barGapInGroup,
  pivotAxisStyle,
  pivotTitle,
} from '../pipes'

const columnParallel: VChartSpecPipeline = [
  initColumnParallel,
  stackCornerRadius,
  barMaxWidth,
  barGapInGroup,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  xBand,
  yLinear,
  label,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotColumnParallel: PivotChartSpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initColumnParallel,
    stackCornerRadius,
    barMaxWidth,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    xBand,
    pivotAxisStyle(yLinear),
    label,
    tooltip,
    verticalCrosshairRect,
    colorBarStyleFill(barStyle),
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const columnParallelSpecPipeline = [pivotAdapter(columnParallel, pivotColumnParallel)]
