import type { SpecPipeline, Spec } from 'src/types'
import {
  initColumn,
  datasetXY,
  xBand,
  yLinear,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  stackInverse,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  barMaxWidth,
  columnPolynomialRegressionLine,
  pivotAxisStyle,
  pivotTitle,
} from '../pipes'
import type { PivotChartConstructorOptions } from '@visactor/vtable'

const column: SpecPipeline<Spec> = [
  initColumn,
  stackCornerRadius,
  barMaxWidth,
  stackInverse,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  xBand,
  yLinear,
  label,
  tooltip,
  verticalCrosshairRect,
  colorAdapter(discreteLegend, colorLegend),
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  columnPolynomialRegressionLine,
]

const pivotColumn: SpecPipeline<PivotChartConstructorOptions> = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initColumn,
    stackCornerRadius,
    barMaxWidth,
    stackInverse,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    xBand,
    pivotAxisStyle(yLinear),
    label,
    tooltip,
    verticalCrosshairRect,
    colorBarStyleFill(barStyle),
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
    columnPolynomialRegressionLine,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const columnSpecPipeline: SpecPipeline<Spec | PivotChartConstructorOptions> = [pivotAdapter(column, pivotColumn)]
