import type { SpecPipeline } from 'src/types'
import {
  initColumn,
  datasetXY,
  xBand,
  yLinear,
  percent,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  stackInverse,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
} from '../pipes'

const columnPercent: SpecPipeline = [
  initColumn,
  stackCornerRadius,
  stackInverse,
  colorAdapter(color, linearColor),
  backgroundColor,
  percent,
  datasetXY,
  progressive,
  xBand,
  yLinear,
  label,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotColumnPercent: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initColumn,
    stackCornerRadius,
    stackInverse,
    colorAdapter(color, linearColor),
    percent,
    backgroundColor,
    datasetXY,
    progressive,
    xBand,
    yLinear,
    label,
    tooltip,
    verticalCrosshairRect,
    colorBarStyleFill(barStyle),
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const columnPercentSpecPipeline: SpecPipeline = [pivotAdapter(columnPercent, pivotColumnPercent)]
