import type { SpecPipeline } from 'src/types'
import {
  initColumn,
  datasetXY,
  xBand,
  yLinear,
  percent,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  stackInverse,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
} from '../pipes'

const columnPercent: SpecPipeline = [
  initColumn,
  stackCornerRadius,
  stackInverse,
  color,
  backgroundColor,
  percent,
  datasetXY,
  xBand,
  yLinear,
  label,
  tooltip,
  verticalCrosshairRect,
  discreteLegend,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotColumnPercent: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initColumn,
    stackCornerRadius,
    stackInverse,
    color,
    percent,
    backgroundColor,
    datasetXY,
    xBand,
    yLinear,
    label,
    tooltip,
    verticalCrosshairRect,
    barStyle,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const columnPercentSpecPipeline: SpecPipeline = [pivotAdapter(columnPercent, pivotColumnPercent)]
