import type { SpecPipeline } from 'src/types'
import {
  backgroundColor,
  color,
  datasetXY,
  datasetPivot,
  initDonut,
  initPivot,
  discreteLegend,
  pivotAdapter,
  pivotColumnDimensions,
  pivotGridStyle,
  pivotIndicators,
  pivotIndicatorsAsRow,
  pivotDiscreteLegend,
  pivotRowDimensions,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  pivotColorLegend,
  pieStyle,
  colorPieStyleFill,
  labelPie,
  pivotHideIndicatorName,
} from '../pipes'

const donut: SpecPipeline = [
  initDonut,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  labelPie,
  colorPieStyleFill(pieStyle),
  colorAdapter(discreteLegend, colorLegend),
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotDonut: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  pivotHideIndicatorName,
  datasetPivot,
  pivotIndicators([
    initDonut,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    labelPie,
    colorPieStyleFill(pieStyle),
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const donutSpecPipeline: SpecPipeline = [pivotAdapter(donut, pivotDonut)]
