import type { SpecPipeline } from 'src/types'
import {
  xBand,
  backgroundColor,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  lineStyle,
  pointStateDimensionHover,
  progressive,
  datasetPrimary,
  datasetSecondary,
  areaStyle,
  barStyle,
  verticalCrosshairRect,
  yLinearSecondary,
  initDualAxisPrimary,
  initDualAxisSecondary,
  labelPrimary,
  labelSecondary,
  tooltipPrimary,
  tooltipSecondary,
  yLinearPrimary,
  dualChartTypePrimary,
  dualChartTypeSecondary,
  seriesDualAxis,
  series,
  colorBarStyleFill,
  colorPointStyleFill,
  colorLineStyleFill,
  colorAreaStyleFill,
  linearColor,
  colorAdapter,
  colorLegend,
  pivotColorLegend,
  linearColorForDualAxis,
} from '../pipes'

const dualAxis: SpecPipeline = [
  seriesDualAxis(
    [
      initDualAxisPrimary,
      dualChartTypePrimary,
      datasetPrimary,
      labelPrimary,
      tooltipPrimary,
      progressive,

      colorBarStyleFill(barStyle),
      colorPointStyleFill(pointStyle),
      pointStateDimensionHover,
      colorLineStyleFill(lineStyle),
      colorAreaStyleFill(areaStyle),
    ],
    [
      initDualAxisSecondary,
      dualChartTypeSecondary,
      datasetSecondary,
      labelSecondary,
      tooltipSecondary,
      progressive,

      colorBarStyleFill(barStyle),
      colorPointStyleFill(pointStyle),
      pointStateDimensionHover,
      colorLineStyleFill(lineStyle),
      colorAreaStyleFill(areaStyle),
    ],
  ),
  xBand,
  yLinearPrimary,
  yLinearSecondary,

  colorAdapter(color, linearColorForDualAxis),
  colorAdapter(discreteLegend, colorLegend),

  backgroundColor,

  verticalCrosshairRect,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotDualAxis: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    series(
      [
        initDualAxisPrimary,
        dualChartTypePrimary,
        datasetPrimary,
        labelPrimary,
        tooltipPrimary,
        progressive,

        colorBarStyleFill(barStyle),
        colorPointStyleFill(pointStyle),
        pointStateDimensionHover,
        colorLineStyleFill(lineStyle),
        colorAreaStyleFill(areaStyle),
      ],
      [
        initDualAxisSecondary,
        dualChartTypeSecondary,
        datasetSecondary,
        labelSecondary,
        tooltipSecondary,
        progressive,

        colorBarStyleFill(barStyle),
        colorPointStyleFill(pointStyle),
        pointStateDimensionHover,
        colorLineStyleFill(lineStyle),
        colorAreaStyleFill(areaStyle),
      ],
    ),
    xBand,
    yLinearPrimary,
    yLinearSecondary,
    colorAdapter(color, linearColor),
    backgroundColor,
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const dualAxisSpecPipeline: SpecPipeline = [pivotAdapter(dualAxis, pivotDualAxis)]
