import type { SpecPipeline, Spec } from 'src/types'
import {
  xBand,
  backgroundColor,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  pointStyle,
  lineStyle,
  pointStateDimensionHover,
  progressive,
  datasetPrimary,
  datasetSecondary,
  areaStyle,
  barStyle,
  verticalCrosshairRect,
  yLinearSecondary,
  initDualAxisPrimary,
  initDualAxisSecondary,
  labelPrimary,
  labelSecondary,
  tooltipPrimary,
  tooltipSecondary,
  yLinearPrimary,
  dualChartTypePrimary,
  dualChartTypeSecondary,
  seriesDualAxis,
  series,
  colorBarStyleFill,
  colorPointStyleFill,
  colorLineStyleFill,
  colorAreaStyleFill,
  linearColor,
  colorAdapter,
  colorLegend,
  pivotColorLegend,
  linearColorForDualAxis,
  annotationAreaBand,
  barMaxWidth,
  barGapInGroup,
  stackCornerRadius,
  pivotTitle,
  pivotAxisStyle,
} from '../pipes'
import type { PivotChartConstructorOptions } from '@visactor/vtable'

const dualAxis: SpecPipeline<Spec> = [
  seriesDualAxis(
    [
      initDualAxisPrimary,
      dualChartTypePrimary,
      datasetPrimary,
      labelPrimary,
      tooltipPrimary,
      progressive,

      barMaxWidth,
      barGapInGroup,
      stackCornerRadius,

      colorBarStyleFill(barStyle),
      colorPointStyleFill(pointStyle),
      pointStateDimensionHover,
      colorLineStyleFill(lineStyle),
      colorAreaStyleFill(areaStyle),
    ],
    [
      initDualAxisSecondary,
      dualChartTypeSecondary,
      datasetSecondary,
      labelSecondary,
      tooltipSecondary,
      progressive,

      barMaxWidth,
      barGapInGroup,
      stackCornerRadius,

      colorBarStyleFill(barStyle),
      colorPointStyleFill(pointStyle),
      pointStateDimensionHover,
      colorLineStyleFill(lineStyle),
      colorAreaStyleFill(areaStyle),
    ],
  ),
  xBand,
  yLinearPrimary,
  yLinearSecondary,

  colorAdapter(color, linearColorForDualAxis),
  colorAdapter(discreteLegend, colorLegend),

  backgroundColor,

  verticalCrosshairRect,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotDualAxis: SpecPipeline<PivotChartConstructorOptions> = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    series(
      [
        initDualAxisPrimary,
        dualChartTypePrimary,
        datasetPrimary,
        labelPrimary,
        tooltipPrimary,
        progressive,

        stackCornerRadius,
        barMaxWidth,
        barGapInGroup,

        colorBarStyleFill(barStyle),
        colorPointStyleFill(pointStyle),
        pointStateDimensionHover,
        colorLineStyleFill(lineStyle),
        colorAreaStyleFill(areaStyle),
      ],
      [
        initDualAxisSecondary,
        dualChartTypeSecondary,
        datasetSecondary,
        labelSecondary,
        tooltipSecondary,
        progressive,

        stackCornerRadius,
        barMaxWidth,
        barGapInGroup,

        colorBarStyleFill(barStyle),
        colorPointStyleFill(pointStyle),
        pointStateDimensionHover,
        colorLineStyleFill(lineStyle),
        colorAreaStyleFill(areaStyle),
      ],
    ),
    xBand,
    yLinearPrimary,
    pivotAxisStyle(yLinearSecondary),
    colorAdapter(color, linearColor),
    backgroundColor,
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const dualAxisSpecPipeline: SpecPipeline<Spec | PivotChartConstructorOptions> = [
  pivotAdapter(dualAxis, pivotDualAxis),
]
