import type { SpecPipeline } from 'src/types'
import {
  xLinear,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotIndicatorsAsCol,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  datasetHistogram,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  initHistogram,
  yLinear,
  verticalCrosshairRect,
} from '../pipes'

const histogram: SpecPipeline = [
  initHistogram,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetHistogram,
  progressive,
  xLinear,
  yLinear,
  label,
  tooltip,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotHistogram: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsCol,
  datasetPivot,
  pivotIndicators([
    initHistogram,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetHistogram,
    progressive,
    xLinear,
    yLinear,
    label,
    tooltip,
    colorBarStyleFill(barStyle),
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const histogramSpecPipeline: SpecPipeline = [pivotAdapter(histogram, pivotHistogram)]
