import type { SpecPipeline, Spec } from 'src/types'
import {
  label,
  xLinear,
  backgroundColor,
  discreteLegend,
  color,
  pivotAdapter,
  initPivot,
  datasetPivot,
  pivotIndicators,
  pivotDiscreteLegend,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  barStyle,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  datasetHistogram,
  progressive,
  colorAdapter,
  linearColor,
  colorLegend,
  colorBarStyleFill,
  pivotColorLegend,
  initHistogram,
  yLinear,
  verticalCrosshairRect,
  tooltipHistogram,
  kdeRegressionLine,
  ecdfRegressionLine,
  pivotTitle,
  pivotAxisStyle,
} from '../pipes'
import type { PivotChartConstructorOptions } from '@visactor/vtable'

const histogram: SpecPipeline<Spec> = [
  initHistogram,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetHistogram,
  progressive,
  xLinear,
  yLinear,
  label,
  tooltipHistogram,
  colorAdapter(discreteLegend, colorLegend),
  verticalCrosshairRect,
  colorBarStyleFill(barStyle),
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  kdeRegressionLine,
  ecdfRegressionLine,
]

const pivotHistogram: SpecPipeline<PivotChartConstructorOptions> = [
  initPivot,
  pivotGridStyle,
  datasetPivot,
  pivotIndicators([
    initHistogram,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetHistogram,
    progressive,
    xLinear,
    pivotAxisStyle(yLinear),
    label,
    tooltipHistogram,
    colorBarStyleFill(barStyle),
    verticalCrosshairRect,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
    kdeRegressionLine,
    ecdfRegressionLine,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const histogramSpecPipeline: SpecPipeline<Spec | PivotChartConstructorOptions> = [
  pivotAdapter(histogram, pivotHistogram),
]
