import type { SpecPipeline, Spec } from 'src/types'
import {
  backgroundColor,
  color,
  datasetXY,
  datasetPivot,
  initPie,
  initPivot,
  discreteLegend,
  pivotAdapter,
  pivotColumnDimensions,
  pivotGridStyle,
  pivotIndicators,
  pivotIndicatorsAsRow,
  pivotDiscreteLegend,
  pivotRowDimensions,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  progressive,
  pieStyle,
  colorPieStyleFill,
  linearColor,
  colorAdapter,
  colorLegend,
  pivotColorLegend,
  labelPie,
  pivotHideIndicatorName,
  pivotTitle,
  addRegionPadding,
} from '../pipes'
import type { PivotChartConstructorOptions } from '@visactor/vtable'

const pie: SpecPipeline<Spec> = [
  initPie,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  colorPieStyleFill(pieStyle),
  colorAdapter(discreteLegend, colorLegend),
  labelPie,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotPie: SpecPipeline<PivotChartConstructorOptions> = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  pivotHideIndicatorName,
  datasetPivot,
  pivotIndicators([
    initPie,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    colorPieStyleFill(pieStyle),
    labelPie,
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
    addRegionPadding,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotTitle,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const pieSpecPipeline: SpecPipeline<Spec | PivotChartConstructorOptions> = [pivotAdapter(pie, pivotPie)]
