import type { SpecPipeline } from 'src/types'
import {
  backgroundColor,
  color,
  datasetXY,
  datasetPivot,
  initPie,
  initPivot,
  label,
  discreteLegend,
  pivotAdapter,
  pivotColumnDimensions,
  pivotGridStyle,
  pivotIndicators,
  pivotIndicatorsAsRow,
  pivotDiscreteLegend,
  pivotRowDimensions,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  progressive,
  pieStyle,
  colorPieStyleFill,
  linearColor,
  colorAdapter,
  colorLegend,
  pivotColorLegend,
} from '../pipes'

const pie: SpecPipeline = [
  initPie,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  colorPieStyleFill(pieStyle),
  colorAdapter(discreteLegend, colorLegend),
  label,
  tooltip,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotPie: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initPie,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    colorPieStyleFill(pieStyle),
    label,
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const pieSpecPipeline: SpecPipeline = [pivotAdapter(pie, pivotPie)]
