import type { SpecPipeline } from 'src/types'
import {
  datasetXY,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  pointStyle,
  lineStyle,
  verticalCrosshairLine,
  pointStateDimensionHover,
  initRadar,
  areaStyle,
  radarAngleAxis,
  radarRadiusAxis,
} from '../pipes'

const radar: SpecPipeline = [
  initRadar,
  color,
  backgroundColor,
  datasetXY,
  radarAngleAxis,
  radarRadiusAxis,
  label,
  tooltip,
  verticalCrosshairLine,
  discreteLegend,
  pointStyle,
  pointStateDimensionHover,
  lineStyle,
  areaStyle,
  // annotationPoint,
  // annotationVerticalLine,
  // annotationHorizontalLine,
  // annotationArea,
]

const pivotRadar: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initRadar,
    color,
    backgroundColor,
    datasetXY,
    radarAngleAxis,
    radarRadiusAxis,
    label,
    tooltip,
    verticalCrosshairLine,
    pointStyle,
    pointStateDimensionHover,
    lineStyle,
    areaStyle,
    // annotationPoint,
    // annotationVerticalLine,
    // annotationHorizontalLine,
    // annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const radarSpecPipeline: SpecPipeline = [pivotAdapter(radar, pivotRadar)]
