import type { SpecPipeline } from 'src/types'
import {
  datasetXY,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  pivotIndicators,
  initPivot,
  datasetPivot,
  pivotAdapter,
  pivotDiscreteLegend,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotRowDimensions,
  pivotColumnDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
  verticalCrosshairRect,
  stackCornerRadius,
  initRoseParallel,
  radiusAxis,
  angleAxis,
  progressive,
  pivotColorLegend,
  colorAdapter,
  linearColor,
  colorLegend,
  roseStyle,
  colorRoseStyleFill,
} from '../pipes'

const roseParallel: SpecPipeline = [
  initRoseParallel,
  stackCornerRadius,
  colorAdapter(color, linearColor),
  backgroundColor,
  datasetXY,
  progressive,
  radiusAxis,
  angleAxis,
  colorRoseStyleFill(roseStyle),
  colorAdapter(discreteLegend, colorLegend),
  label,
  tooltip,
  verticalCrosshairRect,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationAreaBand,
]

const pivotRoseParallel: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initRoseParallel,
    stackCornerRadius,
    colorAdapter(color, linearColor),
    backgroundColor,
    datasetXY,
    progressive,
    radiusAxis,
    angleAxis,
    verticalCrosshairRect,
    colorRoseStyleFill(roseStyle),
    label,
    tooltip,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationAreaBand,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  colorAdapter(pivotDiscreteLegend, pivotColorLegend),
]

export const roseParallelSpecPipeline: SpecPipeline = [pivotAdapter(roseParallel, pivotRoseParallel)]
