import type { SpecPipeline } from 'src/types'
import {
  datasetXY,
  yLinear,
  backgroundColor,
  label,
  tooltip,
  discreteLegend,
  color,
  initPivot,
  datasetPivot,
  pivotDiscreteLegend,
  pivotIndicators,
  pivotAdapter,
  pivotIndicatorsAsRow,
  pivotGridStyle,
  pivotColumnDimensions,
  pivotRowDimensions,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
  pointStyle,
  verticalCrosshairLine,
  xLinear,
  horizontalCrosshairLine,
  pointStateHover,
  initScatter,
  progressive
} from '../pipes'

const scatter: SpecPipeline = [
  initScatter,
  color,
  backgroundColor,
  datasetXY,
  progressive,
  xLinear,
  yLinear,
  label,
  tooltip,
  verticalCrosshairLine,
  horizontalCrosshairLine,
  discreteLegend,
  pointStyle,
  pointStateHover,
  annotationPoint,
  annotationVerticalLine,
  annotationHorizontalLine,
  annotationArea,
]

const pivotScatter: SpecPipeline = [
  initPivot,
  pivotGridStyle,
  pivotIndicatorsAsRow,
  datasetPivot,
  pivotIndicators([
    initScatter,
    color,
    backgroundColor,
    datasetXY,
    progressive,
    xLinear,
    yLinear,
    label,
    tooltip,
    verticalCrosshairLine,
    horizontalCrosshairLine,
    pointStyle,
    pointStateHover,
    annotationPoint,
    annotationVerticalLine,
    annotationHorizontalLine,
    annotationArea,
  ]),
  pivotRowDimensions,
  pivotColumnDimensions,
  pivotDiscreteLegend,
]

export const scatterSpecPipeline: SpecPipeline = [pivotAdapter(scatter, pivotScatter)]
