import { z } from 'zod'
import { zLocale } from '../../i18n'
import {
  zAnnotationArea,
  zAnnotationHorizontalLine,
  zAnnotationPoint,
  zAnnotationVerticalLine,
  zBackgroundColor,
  zBarStyle,
  zColor,
  zCrosshairRect,
  zDataset,
  zDimensions,
  zEncoding,
  zLabel,
  zLegend,
  zMeasureTree,
  zSort,
  zSortLegend,
  zStackCornerRadius,
  zTheme,
  zTooltip,
  zXBandAxis,
  zYLinearAxis,
} from '../../properties'

export const zBoxplot = z.object({
  chartType: z.literal('boxPlot'),
  dataset: zDataset.nullish(),
  encoding: zEncoding.nullish(),
  dimensions: zDimensions.nullish(),
  measures: zMeasureTree.nullish(),
  backgroundColor: zBackgroundColor.nullish(),
  color: zColor.nullish(),
  label: zLabel.nullish(),
  legend: zLegend.nullish(),
  tooltip: zTooltip.nullish(),
  xAxis: zXBandAxis.nullish(),
  yAxis: zYLinearAxis.nullish(),
  sort: zSort.nullish(),
  sortLegent: zSortLegend.nullish(),
  crosshairRect: zCrosshairRect.nullish(),
  stackCornerRadius: zStackCornerRadius.nullish(),
  theme: zTheme.nullish(),
  barStyle: z.array(zBarStyle).or(zBarStyle).nullish(),
  annotationPoint: z.array(zAnnotationPoint).or(zAnnotationPoint).nullish(),
  annotationVerticalLine: z.array(zAnnotationVerticalLine).or(zAnnotationVerticalLine).nullish(),
  annotationHorizontalLine: z.array(zAnnotationHorizontalLine).or(zAnnotationHorizontalLine).nullish(),
  annotationArea: z.array(zAnnotationArea).or(zAnnotationArea).nullish(),
  locale: zLocale.nullish(),
})
