export { label } from './label'
export { labelDualAxis } from './labelDualAxis'
export { labelScatter } from './labelScatter'
export { labelPie } from './labelPie'
export { labelBoxPlot } from './labelBoxPlot'
